<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Gabriel Caruso">
	<meta name="generator" content="HXPHP Framework">
	<meta name="viewport" content="width=device-width, initial-scale=1">
        
	<title><?php echo $view_title; ?></title>
        
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.png">
	<link rel="stylesheet" href="<?php echo CSS; ?>materialize.min.css">	
	<?php 
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>
	<div class="container">